### ISSUE TITLE
Non-admin Accounts cannot access info and search on rootlevel of s3 Account

### ISSUE THREAD

**Issue by jacobsenj** [andersundsehr/aus_driver_amazon_s3#33] opened 2018-04-04 08:33 UTC
I'm having the following issue with a non-admin backend user account:

The account is able to 

- upload, download on root level
- create and delete folders
- upload, download in a subfolder
- show information and do a search in a created subfolder

but cannot

- use information on root level
- search on root level

The admin user is working perfectly fine.

<details>
  <summary>composer.json used to verify</summary>

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        }
    ],
    "name": "Testing",
    "description": "TYPO3 CMS Distribution with console support",
    "license": "GPL-2.0+",
    "require": {
        "typo3/cms": "^8.7.0",
        "typo3/cms-beuser": "^8.7.0",
        "symfony/finder": "^3, !=3.4.7",
        "helhum/typo3-console": "^5.0",
        "andersundsehr/aus-driver-amazon-s3": "^1.7"
    },
    "require-dev": {
        "typo3/testing-framework": "^1.2.2 || ^2.0.1",
        "codeception/codeception": "^2.3",
        "enm1989/chromedriver": "~2.30",
        "fiunchinho/phpunit-randomizer": "~3.0.0",
        "friendsofphp/php-cs-fixer": "^2.0",
        "mikey179/vfsStream": "~1.6.0"
    },
    "scripts": {
        "package-states": [
            "./vendor/bin/typo3cms install:generatepackagestates"
        ],
        "folder-structure": [
            "./vendor/bin/typo3cms install:fixfolderstructure"
        ],
        "pre-deploy": [
            "# Scripts here will be executed by Surf after composer install"
        ],
        "post-autoload-dump": [
            "@package-states",
            "@folder-structure"
        ]
    },
    "extra": {
        "helhum/typo3-console": {
            "install-binary": false,
            "install-extension-dummy": false
        },
        "typo3/cms": {
            "cms-package-dir": "{$vendor-dir}/typo3/cms",
            "web-dir": "web"
        }
    },
    "config": {
        "bin-dir": "./vendor/bin"
    },
    "autoload": {
        "psr-4": {
        }
    },
    "minimum-stability": "beta"
}
```

symfony/finder has a breaking change in 3.4.7, that's why I excluded it in the composer.json
</details>

<details>
  <summary>Non-Admin Screenshots</summary>

The non-admin account has been assigned the filemount and the modules.

![screenshot 2018-04-04 10 31 43](https://user-images.githubusercontent.com/399303/38297028-79e2ebb6-37f3-11e8-9fcc-fb84493a8cbb.png)
![screenshot 2018-04-04 10 31 49](https://user-images.githubusercontent.com/399303/38297031-7b7ac48a-37f3-11e8-9f89-059650c0aa12.png)

## Non-Admin using Information on Rootlevel file
![screenshot 2018-04-04 10 17 26](https://user-images.githubusercontent.com/399303/38296561-ffec4d4e-37f1-11e8-8cdb-d51a8a66791b.png)

## Non-Admin using search on Rootlevel
![screenshot 2018-04-04 10 17 42](https://user-images.githubusercontent.com/399303/38296567-035783fe-37f2-11e8-864c-abe212478008.png)

## Non-Admin using search in a subfolder
![aus_driver_amazon_s3_testing__typo3_cms_8_7_12_](https://user-images.githubusercontent.com/399303/38296860-f1910c7a-37f2-11e8-9282-72efb469ff6f.png)
</details>

<details>
  <summary>Admin Screenshot</summary>

## Admin using information on Rootlevel file
![screenshot 2018-04-04 10 18 42](https://user-images.githubusercontent.com/399303/38296627-2c158980-37f2-11e8-9486-5c241f38b578.png)
</details>

**Comment by Lagerregal** [comment] 2019-07-09 19:40
Hi, thanks for your report and sorry for this really late answer! I can't reproduce this behavior with the latest version anymore. The permissions part was refactored months ago without closing this issue. Is this issue still valid?

**Comment by Lagerregal** [comment] 2021-03-03 20:10
Issue was closed because there was no response after a while.

**Closed by Lagerregal** 2021-03-03 20:10 UTC
Labels: question
